"""
Structural model for the Aegis3D virtual sensor simulator.

The IFC model is the source of truth. This module loads the cached
world-space geometry generated by scripts/data/extract_structural_geometry.py.

This is a reduced-order structural abstraction for sensor-network
simulation. It is not a finite-element model.
"""

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple


PROJECT_ROOT = Path(__file__).resolve().parents[2]

GEOMETRY_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "bim"
    / "structural_geometry.json"
)


@dataclass(frozen=True)
class StructuralComponent:
    """A structural component extracted from the IFC model."""

    ifc_guid: str
    ifc_type: str
    name: str
    storey: str

    bbox_min: Tuple[float, float, float]
    bbox_max: Tuple[float, float, float]
    center: Tuple[float, float, float]

    @property
    def component_type(self) -> str:
        """Return the IFC entity type without the 'Ifc' prefix."""
        return self.ifc_type.removeprefix("Ifc")

    @property
    def x(self) -> float:
        return self.center[0]

    @property
    def y(self) -> float:
        return self.center[1]

    @property
    def z(self) -> float:
        return self.center[2]


class StructuralModel:
    """
    Cached structural representation of the IFC building.

    The model contains the real IFC component identities and
    world-space geometry needed by the virtual sensor network.
    """

    def __init__(
        self,
        geometry_path: Optional[Path] = None,
    ) -> None:
        self.geometry_path = geometry_path or GEOMETRY_PATH
        self._components: Dict[str, StructuralComponent] = {}

        self._load()

    def _load(self) -> None:
        """Load cached structural geometry from disk."""
        if not self.geometry_path.exists():
            raise FileNotFoundError(
                f"Structural geometry cache not found: {self.geometry_path}"
            )

        with self.geometry_path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        components = data.get("components", {})

        for guid, raw in components.items():
            self._components[guid] = StructuralComponent(
                ifc_guid=raw["ifc_guid"],
                ifc_type=raw["ifc_type"],
                name=raw["name"],
                storey=raw["storey"],
                bbox_min=tuple(raw["bbox_min"]),
                bbox_max=tuple(raw["bbox_max"]),
                center=tuple(raw["center"]),
            )

    @property
    def components(self) -> List[StructuralComponent]:
        """Return all structural components."""
        return list(self._components.values())

    @property
    def component_count(self) -> int:
        """Return the number of loaded components."""
        return len(self._components)

    def get_component(
        self,
        ifc_guid: str,
    ) -> Optional[StructuralComponent]:
        """Return a component by IFC GlobalId."""
        return self._components.get(ifc_guid)

    def get_components_by_type(
        self,
        ifc_type: str,
    ) -> List[StructuralComponent]:
        """Return components matching an IFC type."""
        return [
            component
            for component in self._components.values()
            if component.ifc_type == ifc_type
        ]

    def get_components_by_storey(
        self,
        storey: str,
    ) -> List[StructuralComponent]:
        """Return components belonging to a storey."""
        return [
            component
            for component in self._components.values()
            if component.storey == storey
        ]